import os
os.environ["STREAMLIT_SERVER_FILE_WATCHER_TYPE"] = "none"

import streamlit as st
from PIL import Image
import numpy as np
import cv2
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime

st.set_page_config(page_title="ThermaVision AI", layout="wide")

st.markdown("""
<style>
.stApp {
    background: #071426;
    color: #ffffff;
}
.navbar {
    background: linear-gradient(90deg, #061a33, #0b2b52);
    padding: 18px 30px;
    border-bottom: 4px solid #ff8c00;
    border-radius: 0 0 18px 18px;
}
.brand {
    font-size: 34px;
    font-weight: 900;
}
.brand span {
    color: #ff8c00;
}
.nav-sub {
    color: #cbd5e1;
    font-size: 15px;
}
.hero {
    margin-top: 25px;
    padding: 45px;
    border-radius: 22px;
    background:
    linear-gradient(rgba(5, 18, 40, 0.72), rgba(5, 18, 40, 0.88)),
    url("https://images.unsplash.com/photo-1446776811953-b23d57bd21aa");
    background-size: cover;
    background-position: center;
    border: 1px solid rgba(255,255,255,0.15);
}
.title {
    font-size: 52px;
    font-weight: 900;
}
.title span {
    color: #ff8c00;
}
.card {
    padding: 20px;
    border-radius: 16px;
    background: #0b213f;
    border-left: 5px solid #ff8c00;
    box-shadow: 0 8px 24px rgba(0,0,0,0.35);
}
.section-box {
    padding: 25px;
    border-radius: 18px;
    background: #0b213f;
    border: 1px solid rgba(255,255,255,0.12);
    margin-top: 20px;
}
.footer {
    text-align: center;
    padding: 20px;
    color: #94a3b8;
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="navbar">
    <div class="brand">ThermaVision <span>AI</span></div>
    <div class="nav-sub">Space-Inspired Infrared Intelligence Platform</div>
</div>

<div class="hero">
    <div class="title">Infrared Image <span>Analysis System</span></div>
    <h3>Thermal Enhancement + Hotspot Detection + Mission Report</h3>
    <p>
        A mission-focused platform for thermal image enhancement, hotspot detection,
        risk analysis and PDF report generation for rescue, surveillance and remote sensing.
    </p>
</div>
""", unsafe_allow_html=True)

st.markdown("## Mission Applications")

a, b, c = st.columns(3)
with a:
    st.markdown('<div class="card"><h3>🛰 Satellite Analysis</h3><p>Detect high-temperature zones from thermal imagery.</p></div>', unsafe_allow_html=True)
with b:
    st.markdown('<div class="card"><h3>🚨 Rescue Operation</h3><p>Identify possible heat signatures and risk zones.</p></div>', unsafe_allow_html=True)
with c:
    st.markdown('<div class="card"><h3>🌙 Night Surveillance</h3><p>Improve visibility in low-light thermal scenes.</p></div>', unsafe_allow_html=True)

st.markdown("""
<div class="section-box">
<h2>Thermal Processing Lab</h2>
<p>Upload an infrared image to start enhancement, hotspot detection and mission report generation.</p>
</div>
""", unsafe_allow_html=True)

mode = st.selectbox(
    "Select Mission Mode",
    ["Disaster Rescue Scan", "Satellite Thermal Analysis", "Night Surveillance Scan", "Lunar Thermal Scan"]
)

uploaded_file = st.file_uploader("Upload Thermal / Infrared Image", type=["jpg", "jpeg", "png"])


def create_pdf_report(mode, hotspot_count, risk_level, max_area, recommendation):
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)

    pdf.setTitle("ThermaVision AI Report")
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawString(70, 780, "ThermaVision AI - Mission Report")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(70, 740, f"Date & Time: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}")
    pdf.drawString(70, 715, f"Mission Mode: {mode}")
    pdf.drawString(70, 690, f"Hotspots Detected: {hotspot_count}")
    pdf.drawString(70, 665, f"Maximum Hotspot Area: {max_area}")
    pdf.drawString(70, 640, f"Risk Level: {risk_level}")

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(70, 600, "AI Analysis Summary:")

    pdf.setFont("Helvetica", 12)
    text = pdf.beginText(70, 575)
    text.textLines(f"""
The uploaded infrared image was processed using thermal enhancement and hotspot detection.
Bright thermal regions were identified and highlighted using bounding boxes.
This report can support mission teams in quick visual understanding of thermal activity.

Recommendation:
{recommendation}
""")
    pdf.drawText(text)

    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(70, 80, "Generated by ThermaVision AI - Student Prototype")

    pdf.save()
    buffer.seek(0)
    return buffer


if uploaded_file:
    image = Image.open(uploaded_file).convert("RGB")
    img = np.array(image)

    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    gray = cv2.equalizeHist(gray)

    enhanced = cv2.applyColorMap(gray, cv2.COLORMAP_TURBO)
    enhanced = cv2.cvtColor(enhanced, cv2.COLOR_BGR2RGB)

    threshold_value = st.slider("Hotspot Sensitivity", 150, 250, 200)

    _, thresh = cv2.threshold(gray, threshold_value, 255, cv2.THRESH_BINARY)
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    result = enhanced.copy()
    hotspot_count = 0
    max_area = 0

    for cnt in contours:
        area = cv2.contourArea(cnt)
        if area > 80:
            x, y, w, h = cv2.boundingRect(cnt)
            cv2.rectangle(result, (x, y), (x + w, y + h), (255, 255, 255), 3)
            cv2.putText(result, "HOTSPOT", (x, y - 10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)
            hotspot_count += 1
            max_area = max(max_area, int(area))

    if hotspot_count >= 5:
        risk_level = "High"
        recommendation = "Immediate attention required. Multiple strong thermal regions detected."
    elif hotspot_count >= 2:
        risk_level = "Medium"
        recommendation = "Thermal activity found. Manual verification is recommended."
    elif hotspot_count == 1:
        risk_level = "Low"
        recommendation = "Single hotspot found. Monitor the region if needed."
    else:
        risk_level = "Safe"
        recommendation = "No major hotspot detected."

    col1, col2 = st.columns(2)

    with col1:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.subheader("📡 Original Input")
        st.image(image, use_container_width=True)

    with col2:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.subheader("🔥 AI Hotspot Detection Output")
        st.image(result, use_container_width=True)

    st.markdown("## 📊 AI Mission Report")

    r1, r2, r3, r4 = st.columns(4)
    r1.metric("Mission Mode", mode)
    r2.metric("Hotspots Found", hotspot_count)
    r3.metric("Risk Level", risk_level)
    r4.metric("Max Area", max_area)

    if mode == "Disaster Rescue Scan":
        st.warning("Use: Fire zones, trapped person heat signatures, rescue priority areas.")
    elif mode == "Satellite Thermal Analysis":
        st.info("Use: Heat islands, land surface temperature zones, remote sensing.")
    elif mode == "Night Surveillance Scan":
        st.warning("Use: Human/vehicle thermal activity in low-light conditions.")
    else:
        st.info("Use: Lunar surface thermal variation and hotspot study.")

    st.success(recommendation)

    result_img = Image.fromarray(result)
    img_buffer = BytesIO()
    result_img.save(img_buffer, format="PNG")

    st.download_button(
        "⬇ Download Processed Image",
        img_buffer.getvalue(),
        "thermavision_output.png",
        "image/png"
    )

    pdf_buffer = create_pdf_report(mode, hotspot_count, risk_level, max_area, recommendation)

    st.download_button(
        "📄 Download PDF Mission Report",
        pdf_buffer,
        "thermavision_report.pdf",
        "application/pdf"
    )

else:
    st.info("Upload a thermal image to start analysis.")

st.markdown("""
<div class="footer">
© 2026 ThermaVision AI | ISRO-inspired student innovation project
</div>
""", unsafe_allow_html=True)
